sudo: false
language: node_js
node_js:
- '0.10'
- '4'
- node
matrix:
  include:
  - node_js: node
    env: TEST_BROWSERS=true
script: npm run-script ci
deploy:
  provider: npm
  email: mike@cousins.io
  api_key:
    secure: OKeKoplao/n8EEVXJqGCF6QckaaO2chfmOBkqztUTtCCyKE1kPiKPVm2Imte62kHVfGsTeP9xMRlPSRUO9ga0ycZ0rygA4BuXBdfs3TyVFNRipF1vxD/E1tpuEz3FPB7pBDiCfKsrJN0srDHAL/5thBi8sw4j8Q4Fu1ZtJNVR+vmAAlLg5C8djcwQUxbgcJt3nOC9T4lKdgMKdJmlAFx2i9jr7dDkwAdWIAmsJYhDieukhv8y4r4p5nbA14FtzCD8fIpZ5PyQJG8y+BQoOJD/4YePMB5AFUPrgid31cFlzJxeKN3Fx006zsvQtO/tNMtXTUaojSqW5dAPlJg61gDLSgv9MqwyR0dVm0khvQg2R61HGrA+osn5fgMy5vigWnMv+YFoHBguqfKFiqYBhRVDPDIhsp9jPLRAxLXIneeaBaT4GQdOHxErJ9n04ThcqglROL6g3qMCfhtJDnQ5jAjDQY/vxlt5Mz+WlUBiq/QjUQpg4UE0CoxNS3VZxmQofq7rhmDCFuh20G+8uBST9fEb01tlR/PLZFk24h29d3n8Z79XRJk1reBm41mpDhb14PWaJmDT1KwH7jL4lnAQbvHDoPXh1HVlxQZ8k4GmHEsHS9cpWy1qYuc5ony5pbsOKe1/IDHiv29b10wYY7N15LsegPToeZ+H3tAB5K89IGBRlY=
  on:
    node: node
    condition: "$TEST_BROWSERS = true"
    tags: true
    all_branches: true
    repo: tracespace/viewbox
env:
  global:
  - secure: ZDLrgNyY0+8JbQy/4J+8644/cSrKd1xpkIVCV7btXCF1A5/1qatHNr0HZlo7HLRu5CUAaySnhhrrtO1QNWEh9E4aKKul/CVV1mODrz3qC+dLCYBXFKdnUkKyTJmYMos33IlZEIsKcJn6CUS5zVS77jN4Ey3ywwDZHaa0RhGAOK8aYHrzBPTuuB8S6s0oNVrKNwROa/8Y2JV0vJTmdLc9xVZNMxQiqj1Zq0eEE/roaNbVC4rg6Z9akgoBi737V+zSQCxruS3Y5Xz3a9E0Het/poqI1i+3mZPQs2R+lkR4kUFwb4qJOlcwt4zP4GDU0kug6vz9FmRoHRIXiNtrZYepeSyV0AGQUTpdebUigpxORZQx1l2VMfYtOtz2rrpNHxyEsTomN6P5/NOI3vBYTzEKbk7T93TcMWRmu9l7FlEcx518Sbf4O3UmMRmUytpfzGWDmoa/gYKiAR4D2TWyaByDnEPJkh9g4Oepvad3d8mimB5JOE6OMcdKVoT4Ko+FQEwji9SslKYXImjnxa4hQCUSx8WHnhz/iDJcGQ6Sc+Ss3TLCwXbIAbk1csMz/KgD26rFDIYE323rDXpDphua66CIbtI6Z0doqNXqhHSWG/J3QL1vHWHDXLUsZrsjgbZpA0KWd3RkJUVCTLat8CmavjMRqk2Bs3JLjXmzkjxcvknQoRU=
  - secure: Wv1fyPuFoNV1MOuqDKW8ig+aKYqR/g6dsBHVnPaA2bzf5BHIwapMPLe1DZSIkDedmvtTT/JY6j90TP49seBV10u3hD6k1Vdmkp3NyOZFu4l6n0OogBylfSou7be24KEC4acsVYr63PZ9YjlZse1WJVarLUbYAWwn3/YAvPl5ni2g2emcJeztV8t0xRZH4s1Rwt/hKQ0qX1PIvQhtH1J0TRi3ZOfO0BAcLo6EyAJWxCuVBLGsClnv4vm/aa2enwN2wK4hvzjuBNNRKrRd5HdBTEwe1pCS30UIo+9NRyX2vaCthDga+9PsOTGHxA3AKOKaAtWwBq9Gsy/A/Ci4uPVeqBY2yRN/4LXeCM8zgqH1rdFEAjV5CKOK+swsYuq5vB1/u1nhpyUgL2TIq0TTq6DscKGsoj5tKo9Cra6YyUuKRQdkNKTgaLWZzjJ6C5nSNwJiMV/hwnolpiJ0/dcONtY3ZwiHGCYRZLEgFtKvlc3FQWmR4rvWNVmr5XBfHUQp2oECQen2Klp3KZKnRKCTQ46ybSPazIniB92D04ijHp8miupDCKW3dUmZkq2ndAuZOg7Y64TbCqK8vajnufca2zS4da+Vtf+tXJwAKRrdZnc9eCUKB2uriaJglY6uBl1gHZQ2TTu1RM19C8VvL8mjY8NqHlVJ1xhuFHNnYA16Lz0qZEM=
